//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPC.DynamicForms.Web.RT.Services.Request {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://STPC.LiSim.Abc")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AplicationNameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FormIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PageFlowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageFlowStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> WorkFlowStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AplicationNameId {
            get {
                return this.AplicationNameIdField;
            }
            set {
                if ((this.AplicationNameIdField.Equals(value) != true)) {
                    this.AplicationNameIdField = value;
                    this.RaisePropertyChanged("AplicationNameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedTo {
            get {
                return this.AssignedToField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedToField, value) != true)) {
                    this.AssignedToField = value;
                    this.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FormId {
            get {
                return this.FormIdField;
            }
            set {
                if ((this.FormIdField.Equals(value) != true)) {
                    this.FormIdField = value;
                    this.RaisePropertyChanged("FormId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PageFlowId {
            get {
                return this.PageFlowIdField;
            }
            set {
                if ((this.PageFlowIdField.Equals(value) != true)) {
                    this.PageFlowIdField = value;
                    this.RaisePropertyChanged("PageFlowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageFlowState {
            get {
                return this.PageFlowStateField;
            }
            set {
                if ((object.ReferenceEquals(this.PageFlowStateField, value) != true)) {
                    this.PageFlowStateField = value;
                    this.RaisePropertyChanged("PageFlowState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Updated {
            get {
                return this.UpdatedField;
            }
            set {
                if ((this.UpdatedField.Equals(value) != true)) {
                    this.UpdatedField = value;
                    this.RaisePropertyChanged("Updated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> WorkFlowState {
            get {
                return this.WorkFlowStateField;
            }
            set {
                if ((this.WorkFlowStateField.Equals(value) != true)) {
                    this.WorkFlowStateField = value;
                    this.RaisePropertyChanged("WorkFlowState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormData", Namespace="http://schemas.datacontract.org/2004/07/STPC.DynamicForms.Services.RequestService" +
        "")]
    [System.SerializableAttribute()]
    public partial class FormData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FormIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FormPageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormPageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PageFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PanelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PanelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FormId {
            get {
                return this.FormIdField;
            }
            set {
                if ((this.FormIdField.Equals(value) != true)) {
                    this.FormIdField = value;
                    this.RaisePropertyChanged("FormId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName {
            get {
                return this.FormNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormNameField, value) != true)) {
                    this.FormNameField = value;
                    this.RaisePropertyChanged("FormName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FormPageId {
            get {
                return this.FormPageIdField;
            }
            set {
                if ((this.FormPageIdField.Equals(value) != true)) {
                    this.FormPageIdField = value;
                    this.RaisePropertyChanged("FormPageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormPageName {
            get {
                return this.FormPageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormPageNameField, value) != true)) {
                    this.FormPageNameField = value;
                    this.RaisePropertyChanged("FormPageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PageFields {
            get {
                return this.PageFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.PageFieldsField, value) != true)) {
                    this.PageFieldsField = value;
                    this.RaisePropertyChanged("PageFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PanelId {
            get {
                return this.PanelIdField;
            }
            set {
                if ((this.PanelIdField.Equals(value) != true)) {
                    this.PanelIdField = value;
                    this.RaisePropertyChanged("PanelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanelName {
            get {
                return this.PanelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PanelNameField, value) != true)) {
                    this.PanelNameField = value;
                    this.RaisePropertyChanged("PanelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AplicationName", Namespace="http://STPC.LiSim.Abc")]
    [System.SerializableAttribute()]
    public partial class AplicationName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.AdCampaign> AdCampaignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Category> CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.Hierarchy> HierarchyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.MenuItem> MenuItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.PerformanceIndicator> PerformanceIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.Report> ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Request> RequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.AdCampaign> AdCampaign {
            get {
                return this.AdCampaignField;
            }
            set {
                if ((object.ReferenceEquals(this.AdCampaignField, value) != true)) {
                    this.AdCampaignField = value;
                    this.RaisePropertyChanged("AdCampaign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Category> Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.Hierarchy> Hierarchy {
            get {
                return this.HierarchyField;
            }
            set {
                if ((object.ReferenceEquals(this.HierarchyField, value) != true)) {
                    this.HierarchyField = value;
                    this.RaisePropertyChanged("Hierarchy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.MenuItem> MenuItem {
            get {
                return this.MenuItemField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemField, value) != true)) {
                    this.MenuItemField = value;
                    this.RaisePropertyChanged("MenuItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.PerformanceIndicator> PerformanceIndicator {
            get {
                return this.PerformanceIndicatorField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceIndicatorField, value) != true)) {
                    this.PerformanceIndicatorField = value;
                    this.RaisePropertyChanged("PerformanceIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.Report> Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Request> Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdCampaign", Namespace="http://STPC.LiSim.Abc", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class AdCampaign : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApplyToChildsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BeginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Hierarchy_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ApplyToChilds {
            get {
                return this.ApplyToChildsField;
            }
            set {
                if ((this.ApplyToChildsField.Equals(value) != true)) {
                    this.ApplyToChildsField = value;
                    this.RaisePropertyChanged("ApplyToChilds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginDate {
            get {
                return this.BeginDateField;
            }
            set {
                if ((this.BeginDateField.Equals(value) != true)) {
                    this.BeginDateField = value;
                    this.RaisePropertyChanged("BeginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hierarchy_id {
            get {
                return this.Hierarchy_idField;
            }
            set {
                if ((this.Hierarchy_idField.Equals(value) != true)) {
                    this.Hierarchy_idField = value;
                    this.RaisePropertyChanged("Hierarchy_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://STPC.LiSim.Abc", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Option> OptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Option> Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://STPC.LiSim.Abc")]
    [System.SerializableAttribute()]
    public partial class MenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STPC.DynamicForms.Web.RT.Services.Request.AplicationName AplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AplicationNameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.MenuItem> ChildsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FormStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FormUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentMenuItemUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STPC.DynamicForms.Web.RT.Services.Request.AplicationName AplicationName {
            get {
                return this.AplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AplicationNameField, value) != true)) {
                    this.AplicationNameField = value;
                    this.RaisePropertyChanged("AplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AplicationNameId {
            get {
                return this.AplicationNameIdField;
            }
            set {
                if ((this.AplicationNameIdField.Equals(value) != true)) {
                    this.AplicationNameIdField = value;
                    this.RaisePropertyChanged("AplicationNameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.MenuItem> Childs {
            get {
                return this.ChildsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildsField, value) != true)) {
                    this.ChildsField = value;
                    this.RaisePropertyChanged("Childs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Controller {
            get {
                return this.ControllerField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerField, value) != true)) {
                    this.ControllerField = value;
                    this.RaisePropertyChanged("Controller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> FormState {
            get {
                return this.FormStateField;
            }
            set {
                if ((this.FormStateField.Equals(value) != true)) {
                    this.FormStateField = value;
                    this.RaisePropertyChanged("FormState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> FormUid {
            get {
                return this.FormUidField;
            }
            set {
                if ((this.FormUidField.Equals(value) != true)) {
                    this.FormUidField = value;
                    this.RaisePropertyChanged("FormUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentMenuItemUid {
            get {
                return this.ParentMenuItemUidField;
            }
            set {
                if ((this.ParentMenuItemUidField.Equals(value) != true)) {
                    this.ParentMenuItemUidField = value;
                    this.RaisePropertyChanged("ParentMenuItemUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Uid {
            get {
                return this.UidField;
            }
            set {
                if ((this.UidField.Equals(value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceIndicator", Namespace="http://STPC.LiSim.Abc")]
    [System.SerializableAttribute()]
    public partial class PerformanceIndicator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STPC.DynamicForms.Web.RT.Services.Request.AplicationName AplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AplicationNameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STPC.DynamicForms.Web.Common.Services.Users.Hierarchy HierarchyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndicatorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STPC.DynamicForms.Web.Common.Services.Users.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STPC.DynamicForms.Web.Common.Services.Users.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViolationMaxvalueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViolationMinvalueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WarningMaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WarningMinValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STPC.DynamicForms.Web.RT.Services.Request.AplicationName AplicationName {
            get {
                return this.AplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AplicationNameField, value) != true)) {
                    this.AplicationNameField = value;
                    this.RaisePropertyChanged("AplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AplicationNameId {
            get {
                return this.AplicationNameIdField;
            }
            set {
                if ((this.AplicationNameIdField.Equals(value) != true)) {
                    this.AplicationNameIdField = value;
                    this.RaisePropertyChanged("AplicationNameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STPC.DynamicForms.Web.Common.Services.Users.Hierarchy Hierarchy {
            get {
                return this.HierarchyField;
            }
            set {
                if ((object.ReferenceEquals(this.HierarchyField, value) != true)) {
                    this.HierarchyField = value;
                    this.RaisePropertyChanged("Hierarchy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndicatorType {
            get {
                return this.IndicatorTypeField;
            }
            set {
                if ((this.IndicatorTypeField.Equals(value) != true)) {
                    this.IndicatorTypeField = value;
                    this.RaisePropertyChanged("IndicatorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((this.LastModifiedByField.Equals(value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STPC.DynamicForms.Web.Common.Services.Users.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STPC.DynamicForms.Web.Common.Services.Users.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViolationMaxvalue {
            get {
                return this.ViolationMaxvalueField;
            }
            set {
                if ((this.ViolationMaxvalueField.Equals(value) != true)) {
                    this.ViolationMaxvalueField = value;
                    this.RaisePropertyChanged("ViolationMaxvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViolationMinvalue {
            get {
                return this.ViolationMinvalueField;
            }
            set {
                if ((this.ViolationMinvalueField.Equals(value) != true)) {
                    this.ViolationMinvalueField = value;
                    this.RaisePropertyChanged("ViolationMinvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WarningMaxValue {
            get {
                return this.WarningMaxValueField;
            }
            set {
                if ((this.WarningMaxValueField.Equals(value) != true)) {
                    this.WarningMaxValueField = value;
                    this.RaisePropertyChanged("WarningMaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WarningMinValue {
            get {
                return this.WarningMinValueField;
            }
            set {
                if ((this.WarningMinValueField.Equals(value) != true)) {
                    this.WarningMinValueField = value;
                    this.RaisePropertyChanged("WarningMinValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Option", Namespace="http://STPC.LiSim.Abc", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Option : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STPC.DynamicForms.Web.RT.Services.Request.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Category_UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STPC.DynamicForms.Web.RT.Services.Request.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category_Uid {
            get {
                return this.Category_UidField;
            }
            set {
                if ((this.Category_UidField.Equals(value) != true)) {
                    this.Category_UidField = value;
                    this.RaisePropertyChanged("Category_Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Uid {
            get {
                return this.UidField;
            }
            set {
                if ((this.UidField.Equals(value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Request.IRequestService")]
    public interface IRequestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequest", ReplyAction="http://tempuri.org/IRequestService/GetRequestResponse")]
        System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Request> GetRequest(System.Collections.Generic.Dictionary<string, string> values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequestDynamic", ReplyAction="http://tempuri.org/IRequestService/GetRequestDynamicResponse")]
        STPC.DynamicForms.Core.MyViewModel GetRequestDynamic(System.Collections.Generic.List<STPC.DynamicForms.Core.ReportParameters> values, System.Collections.Generic.Dictionary<string, string> ParametersRequestTable, string RequestType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequestDynamicSearcher", ReplyAction="http://tempuri.org/IRequestService/GetRequestDynamicSearcherResponse")]
        STPC.DynamicForms.Core.MyViewModel GetRequestDynamicSearcher(System.Collections.Generic.List<STPC.DynamicForms.Core.ReportParameters> values, System.Collections.Generic.Dictionary<string, string> ParametersRequestTable, string RequestType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequestByProcedure", ReplyAction="http://tempuri.org/IRequestService/GetRequestByProcedureResponse")]
        STPC.DynamicForms.Core.MyViewModel GetRequestByProcedure(string iStoredProcedureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetIndicatorByProcedure", ReplyAction="http://tempuri.org/IRequestService/GetIndicatorByProcedureResponse")]
        STPC.DynamicForms.Core.MyViewModel GetIndicatorByProcedure(string storedProcedure, System.Collections.Generic.Dictionary<string, string> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequestsByParamProcedure", ReplyAction="http://tempuri.org/IRequestService/GetRequestsByParamProcedureResponse")]
        STPC.DynamicForms.Core.MyViewModel GetRequestsByParamProcedure(string iStoredProcedureName, string userName, int offSet, int fetch, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetSchemaTable", ReplyAction="http://tempuri.org/IRequestService/GetSchemaTableResponse")]
        STPC.DynamicForms.Core.MyViewModel GetSchemaTable(string tableName, int nodeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/InsertAtributesHierarchy", ReplyAction="http://tempuri.org/IRequestService/InsertAtributesHierarchyResponse")]
        void InsertAtributesHierarchy(System.Collections.Generic.Dictionary<string, string> listFieldsValues, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/UpdateAtributesHierarchy", ReplyAction="http://tempuri.org/IRequestService/UpdateAtributesHierarchyResponse")]
        void UpdateAtributesHierarchy(System.Collections.Generic.Dictionary<string, string> listFieldsValues, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/FindRecordIntoAtributeTable", ReplyAction="http://tempuri.org/IRequestService/FindRecordIntoAtributeTableResponse")]
        int FindRecordIntoAtributeTable(string tableName, int nodeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/CreateRequest", ReplyAction="http://tempuri.org/IRequestService/CreateRequestResponse")]
        int CreateRequest(STPC.DynamicForms.Web.RT.Services.Request.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/CreatePageFlowStepInstance", ReplyAction="http://tempuri.org/IRequestService/CreatePageFlowStepInstanceResponse")]
        string CreatePageFlowStepInstance(STPC.DynamicForms.Web.RT.Services.Request.Request request, System.Guid formPageId, string formName, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/NewPageFlowStepInstance", ReplyAction="http://tempuri.org/IRequestService/NewPageFlowStepInstanceResponse")]
        string NewPageFlowStepInstance(STPC.DynamicForms.Web.RT.Services.Request.Request request, STPC.DynamicForms.Web.RT.Services.Request.FormData pageData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetPageFlowStepInstance", ReplyAction="http://tempuri.org/IRequestService/GetPageFlowStepInstanceResponse")]
        System.Collections.Generic.List<STPC.DynamicForms.Core.Values> GetPageFlowStepInstance(int requestId, System.Guid formPageId, System.Guid PageFlowId, string formName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequestById", ReplyAction="http://tempuri.org/IRequestService/GetRequestByIdResponse")]
        STPC.DynamicForms.Web.RT.Services.Request.Request GetRequestById(int iRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/UpdateRequest", ReplyAction="http://tempuri.org/IRequestService/UpdateRequestResponse")]
        void UpdateRequest(STPC.DynamicForms.Web.RT.Services.Request.Request request, System.Guid formPageId, string formName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/InsertDecisionEngineResult", ReplyAction="http://tempuri.org/IRequestService/InsertDecisionEngineResultResponse")]
        void InsertDecisionEngineResult(System.Xml.XmlElement xmlDecisionEngineResult, int requestId, string updatedBy, string tableToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetUserFormPageActionsByState", ReplyAction="http://tempuri.org/IRequestService/GetUserFormPageActionsByStateResponse")]
        System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.FormPageActions> GetUserFormPageActionsByState(string roleName, System.Guid pageId, System.Guid formStateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/getFieldByPage", ReplyAction="http://tempuri.org/IRequestService/getFieldByPageResponse")]
        System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.PageField> getFieldByPage(System.Guid uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestServiceChannel : STPC.DynamicForms.Web.RT.Services.Request.IRequestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestServiceClient : System.ServiceModel.ClientBase<STPC.DynamicForms.Web.RT.Services.Request.IRequestService>, STPC.DynamicForms.Web.RT.Services.Request.IRequestService {
        
        public RequestServiceClient() {
        }
        
        public RequestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<STPC.DynamicForms.Web.RT.Services.Request.Request> GetRequest(System.Collections.Generic.Dictionary<string, string> values) {
            return base.Channel.GetRequest(values);
        }
        
        public STPC.DynamicForms.Core.MyViewModel GetRequestDynamic(System.Collections.Generic.List<STPC.DynamicForms.Core.ReportParameters> values, System.Collections.Generic.Dictionary<string, string> ParametersRequestTable, string RequestType) {
            return base.Channel.GetRequestDynamic(values, ParametersRequestTable, RequestType);
        }
        
        public STPC.DynamicForms.Core.MyViewModel GetRequestDynamicSearcher(System.Collections.Generic.List<STPC.DynamicForms.Core.ReportParameters> values, System.Collections.Generic.Dictionary<string, string> ParametersRequestTable, string RequestType) {
            return base.Channel.GetRequestDynamicSearcher(values, ParametersRequestTable, RequestType);
        }
        
        public STPC.DynamicForms.Core.MyViewModel GetRequestByProcedure(string iStoredProcedureName) {
            return base.Channel.GetRequestByProcedure(iStoredProcedureName);
        }
        
        public STPC.DynamicForms.Core.MyViewModel GetIndicatorByProcedure(string storedProcedure, System.Collections.Generic.Dictionary<string, string> parameters) {
            return base.Channel.GetIndicatorByProcedure(storedProcedure, parameters);
        }
        
        public STPC.DynamicForms.Core.MyViewModel GetRequestsByParamProcedure(string iStoredProcedureName, string userName, int offSet, int fetch, string filter) {
            return base.Channel.GetRequestsByParamProcedure(iStoredProcedureName, userName, offSet, fetch, filter);
        }
        
        public STPC.DynamicForms.Core.MyViewModel GetSchemaTable(string tableName, int nodeId) {
            return base.Channel.GetSchemaTable(tableName, nodeId);
        }
        
        public void InsertAtributesHierarchy(System.Collections.Generic.Dictionary<string, string> listFieldsValues, string table) {
            base.Channel.InsertAtributesHierarchy(listFieldsValues, table);
        }
        
        public void UpdateAtributesHierarchy(System.Collections.Generic.Dictionary<string, string> listFieldsValues, string table) {
            base.Channel.UpdateAtributesHierarchy(listFieldsValues, table);
        }
        
        public int FindRecordIntoAtributeTable(string tableName, int nodeId) {
            return base.Channel.FindRecordIntoAtributeTable(tableName, nodeId);
        }
        
        public int CreateRequest(STPC.DynamicForms.Web.RT.Services.Request.Request request) {
            return base.Channel.CreateRequest(request);
        }
        
        public string CreatePageFlowStepInstance(STPC.DynamicForms.Web.RT.Services.Request.Request request, System.Guid formPageId, string formName, string xml) {
            return base.Channel.CreatePageFlowStepInstance(request, formPageId, formName, xml);
        }
        
        public string NewPageFlowStepInstance(STPC.DynamicForms.Web.RT.Services.Request.Request request, STPC.DynamicForms.Web.RT.Services.Request.FormData pageData) {
            return base.Channel.NewPageFlowStepInstance(request, pageData);
        }
        
        public System.Collections.Generic.List<STPC.DynamicForms.Core.Values> GetPageFlowStepInstance(int requestId, System.Guid formPageId, System.Guid PageFlowId, string formName) {
            return base.Channel.GetPageFlowStepInstance(requestId, formPageId, PageFlowId, formName);
        }
        
        public STPC.DynamicForms.Web.RT.Services.Request.Request GetRequestById(int iRequestId) {
            return base.Channel.GetRequestById(iRequestId);
        }
        
        public void UpdateRequest(STPC.DynamicForms.Web.RT.Services.Request.Request request, System.Guid formPageId, string formName) {
            base.Channel.UpdateRequest(request, formPageId, formName);
        }
        
        public void InsertDecisionEngineResult(System.Xml.XmlElement xmlDecisionEngineResult, int requestId, string updatedBy, string tableToInsert) {
            base.Channel.InsertDecisionEngineResult(xmlDecisionEngineResult, requestId, updatedBy, tableToInsert);
        }
        
        public System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.FormPageActions> GetUserFormPageActionsByState(string roleName, System.Guid pageId, System.Guid formStateId) {
            return base.Channel.GetUserFormPageActionsByState(roleName, pageId, formStateId);
        }
        
        public System.Collections.Generic.List<STPC.DynamicForms.Web.Common.Services.Users.PageField> getFieldByPage(System.Guid uid) {
            return base.Channel.getFieldByPage(uid);
        }
    }
}
