//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPC.DynamicForms.DecisionEngine.ScortoProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScortoProxy.ScoringServiceSoap")]
    public interface ScoringServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginUser(string userName, string password);
        
        // CODEGEN: Generating message contract since message GetStrategyListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStrategyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyListResponse GetStrategyList(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyListRequest request);
        
        // CODEGEN: Generating message contract since message GetPublicNameListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPublicNameList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetPublicNameListResponse GetPublicNameList(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetPublicNameListRequest request);
        
        // CODEGEN: Generating message contract since message CreateApplicationByStrategyIdRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateApplicationByStrategyId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByStrategyIdResponse CreateApplicationByStrategyId(STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByStrategyIdRequest request);
        
        // CODEGEN: Generating message contract since message CreateApplicationByPublicNameIdRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateApplicationByPublicNameId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByPublicNameIdResponse CreateApplicationByPublicNameId(STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByPublicNameIdRequest request);
        
        // CODEGEN: Generating message contract since message GetApplicationStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApplicationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationStatusResponse GetApplicationStatus(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationStatusRequest request);
        
        // CODEGEN: Generating message contract since message GetApplicationResultRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApplicationResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationResultResponse GetApplicationResult(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationResultRequest request);
        
        // CODEGEN: Generating message contract since message GetStrategySchemaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStrategySchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategySchemaResponse GetStrategySchema(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategySchemaRequest request);
        
        // CODEGEN: Generating message contract since message GetStrategyExampleXMLRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStrategyExampleXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyExampleXMLResponse GetStrategyExampleXML(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyExampleXMLRequest request);
        
        // CODEGEN: Generating message contract since message GetLatestStrategyIdByStrategyNameRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestStrategyIdByStrategyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLatestStrategyIdByStrategyNameResponse GetLatestStrategyIdByStrategyName(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLatestStrategyIdByStrategyNameRequest request);
        
        // CODEGEN: Generating message contract since message GetLinkedStrategiesByPublicNameIdRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLinkedStrategiesByPublicNameId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLinkedStrategiesByPublicNameIdResponse GetLinkedStrategiesByPublicNameId(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLinkedStrategiesByPublicNameIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ticket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ticketIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TicketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("TicketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStrategyList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStrategyListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        public GetStrategyListRequest() {
        }
        
        public GetStrategyListRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket) {
            this.Ticket = Ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStrategyListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStrategyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetStrategyListResult;
        
        public GetStrategyListResponse() {
        }
        
        public GetStrategyListResponse(string GetStrategyListResult) {
            this.GetStrategyListResult = GetStrategyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicNameList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPublicNameListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        public GetPublicNameListRequest() {
        }
        
        public GetPublicNameListRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket) {
            this.Ticket = Ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicNameListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPublicNameListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetPublicNameListResult;
        
        public GetPublicNameListResponse() {
        }
        
        public GetPublicNameListResponse(string GetPublicNameListResult) {
            this.GetPublicNameListResult = GetPublicNameListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateApplicationByStrategyId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateApplicationByStrategyIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int strategyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string parametersData;
        
        public CreateApplicationByStrategyIdRequest() {
        }
        
        public CreateApplicationByStrategyIdRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int strategyId, string parametersData) {
            this.Ticket = Ticket;
            this.strategyId = strategyId;
            this.parametersData = parametersData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateApplicationByStrategyIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateApplicationByStrategyIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long CreateApplicationByStrategyIdResult;
        
        public CreateApplicationByStrategyIdResponse() {
        }
        
        public CreateApplicationByStrategyIdResponse(long CreateApplicationByStrategyIdResult) {
            this.CreateApplicationByStrategyIdResult = CreateApplicationByStrategyIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateApplicationByPublicNameId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateApplicationByPublicNameIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int publicNameId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string parametersData;
        
        public CreateApplicationByPublicNameIdRequest() {
        }
        
        public CreateApplicationByPublicNameIdRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int publicNameId, string parametersData) {
            this.Ticket = Ticket;
            this.publicNameId = publicNameId;
            this.parametersData = parametersData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateApplicationByPublicNameIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateApplicationByPublicNameIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long CreateApplicationByPublicNameIdResult;
        
        public CreateApplicationByPublicNameIdResponse() {
        }
        
        public CreateApplicationByPublicNameIdResponse(long CreateApplicationByPublicNameIdResult) {
            this.CreateApplicationByPublicNameIdResult = CreateApplicationByPublicNameIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApplicationStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetApplicationStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long applicationID;
        
        public GetApplicationStatusRequest() {
        }
        
        public GetApplicationStatusRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, long applicationID) {
            this.Ticket = Ticket;
            this.applicationID = applicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApplicationStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetApplicationStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetApplicationStatusResult;
        
        public GetApplicationStatusResponse() {
        }
        
        public GetApplicationStatusResponse(string GetApplicationStatusResult) {
            this.GetApplicationStatusResult = GetApplicationStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApplicationResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetApplicationResultRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long applicationID;
        
        public GetApplicationResultRequest() {
        }
        
        public GetApplicationResultRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, long applicationID) {
            this.Ticket = Ticket;
            this.applicationID = applicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApplicationResultResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetApplicationResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetApplicationResultResult;
        
        public GetApplicationResultResponse() {
        }
        
        public GetApplicationResultResponse(string GetApplicationResultResult) {
            this.GetApplicationResultResult = GetApplicationResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStrategySchema", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStrategySchemaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int strategyId;
        
        public GetStrategySchemaRequest() {
        }
        
        public GetStrategySchemaRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int strategyId) {
            this.Ticket = Ticket;
            this.strategyId = strategyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStrategySchemaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStrategySchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetStrategySchemaResult;
        
        public GetStrategySchemaResponse() {
        }
        
        public GetStrategySchemaResponse(string GetStrategySchemaResult) {
            this.GetStrategySchemaResult = GetStrategySchemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStrategyExampleXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStrategyExampleXMLRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int strategyId;
        
        public GetStrategyExampleXMLRequest() {
        }
        
        public GetStrategyExampleXMLRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int strategyId) {
            this.Ticket = Ticket;
            this.strategyId = strategyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStrategyExampleXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStrategyExampleXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetStrategyExampleXMLResult;
        
        public GetStrategyExampleXMLResponse() {
        }
        
        public GetStrategyExampleXMLResponse(string GetStrategyExampleXMLResult) {
            this.GetStrategyExampleXMLResult = GetStrategyExampleXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestStrategyIdByStrategyName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLatestStrategyIdByStrategyNameRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strategyName;
        
        public GetLatestStrategyIdByStrategyNameRequest() {
        }
        
        public GetLatestStrategyIdByStrategyNameRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, string strategyName) {
            this.Ticket = Ticket;
            this.strategyName = strategyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestStrategyIdByStrategyNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLatestStrategyIdByStrategyNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetLatestStrategyIdByStrategyNameResult;
        
        public GetLatestStrategyIdByStrategyNameResponse() {
        }
        
        public GetLatestStrategyIdByStrategyNameResponse(int GetLatestStrategyIdByStrategyNameResult) {
            this.GetLatestStrategyIdByStrategyNameResult = GetLatestStrategyIdByStrategyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLinkedStrategiesByPublicNameId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLinkedStrategiesByPublicNameIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int publicNameId;
        
        public GetLinkedStrategiesByPublicNameIdRequest() {
        }
        
        public GetLinkedStrategiesByPublicNameIdRequest(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int publicNameId) {
            this.Ticket = Ticket;
            this.publicNameId = publicNameId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLinkedStrategiesByPublicNameIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLinkedStrategiesByPublicNameIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetLinkedStrategiesByPublicNameIdResult;
        
        public GetLinkedStrategiesByPublicNameIdResponse() {
        }
        
        public GetLinkedStrategiesByPublicNameIdResponse(string GetLinkedStrategiesByPublicNameIdResult) {
            this.GetLinkedStrategiesByPublicNameIdResult = GetLinkedStrategiesByPublicNameIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScoringServiceSoapChannel : STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScoringServiceSoapClient : System.ServiceModel.ClientBase<STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap>, STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap {
        
        public ScoringServiceSoapClient() {
        }
        
        public ScoringServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScoringServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoringServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoringServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoginUser(string userName, string password) {
            return base.Channel.LoginUser(userName, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyListResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetStrategyList(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyListRequest request) {
            return base.Channel.GetStrategyList(request);
        }
        
        public string GetStrategyList(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyListRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyListRequest();
            inValue.Ticket = Ticket;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyListResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetStrategyList(inValue);
            return retVal.GetStrategyListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetPublicNameListResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetPublicNameList(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetPublicNameListRequest request) {
            return base.Channel.GetPublicNameList(request);
        }
        
        public string GetPublicNameList(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetPublicNameListRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetPublicNameListRequest();
            inValue.Ticket = Ticket;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetPublicNameListResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetPublicNameList(inValue);
            return retVal.GetPublicNameListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByStrategyIdResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.CreateApplicationByStrategyId(STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByStrategyIdRequest request) {
            return base.Channel.CreateApplicationByStrategyId(request);
        }
        
        public long CreateApplicationByStrategyId(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int strategyId, string parametersData) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByStrategyIdRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByStrategyIdRequest();
            inValue.Ticket = Ticket;
            inValue.strategyId = strategyId;
            inValue.parametersData = parametersData;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByStrategyIdResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).CreateApplicationByStrategyId(inValue);
            return retVal.CreateApplicationByStrategyIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByPublicNameIdResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.CreateApplicationByPublicNameId(STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByPublicNameIdRequest request) {
            return base.Channel.CreateApplicationByPublicNameId(request);
        }
        
        public long CreateApplicationByPublicNameId(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int publicNameId, string parametersData) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByPublicNameIdRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByPublicNameIdRequest();
            inValue.Ticket = Ticket;
            inValue.publicNameId = publicNameId;
            inValue.parametersData = parametersData;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.CreateApplicationByPublicNameIdResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).CreateApplicationByPublicNameId(inValue);
            return retVal.CreateApplicationByPublicNameIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationStatusResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetApplicationStatus(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationStatusRequest request) {
            return base.Channel.GetApplicationStatus(request);
        }
        
        public string GetApplicationStatus(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, long applicationID) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationStatusRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationStatusRequest();
            inValue.Ticket = Ticket;
            inValue.applicationID = applicationID;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationStatusResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetApplicationStatus(inValue);
            return retVal.GetApplicationStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationResultResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetApplicationResult(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationResultRequest request) {
            return base.Channel.GetApplicationResult(request);
        }
        
        public string GetApplicationResult(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, long applicationID) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationResultRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationResultRequest();
            inValue.Ticket = Ticket;
            inValue.applicationID = applicationID;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetApplicationResultResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetApplicationResult(inValue);
            return retVal.GetApplicationResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategySchemaResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetStrategySchema(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategySchemaRequest request) {
            return base.Channel.GetStrategySchema(request);
        }
        
        public string GetStrategySchema(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int strategyId) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategySchemaRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategySchemaRequest();
            inValue.Ticket = Ticket;
            inValue.strategyId = strategyId;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategySchemaResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetStrategySchema(inValue);
            return retVal.GetStrategySchemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyExampleXMLResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetStrategyExampleXML(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyExampleXMLRequest request) {
            return base.Channel.GetStrategyExampleXML(request);
        }
        
        public string GetStrategyExampleXML(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int strategyId) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyExampleXMLRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyExampleXMLRequest();
            inValue.Ticket = Ticket;
            inValue.strategyId = strategyId;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetStrategyExampleXMLResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetStrategyExampleXML(inValue);
            return retVal.GetStrategyExampleXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLatestStrategyIdByStrategyNameResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetLatestStrategyIdByStrategyName(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLatestStrategyIdByStrategyNameRequest request) {
            return base.Channel.GetLatestStrategyIdByStrategyName(request);
        }
        
        public int GetLatestStrategyIdByStrategyName(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, string strategyName) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLatestStrategyIdByStrategyNameRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLatestStrategyIdByStrategyNameRequest();
            inValue.Ticket = Ticket;
            inValue.strategyName = strategyName;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLatestStrategyIdByStrategyNameResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetLatestStrategyIdByStrategyName(inValue);
            return retVal.GetLatestStrategyIdByStrategyNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLinkedStrategiesByPublicNameIdResponse STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap.GetLinkedStrategiesByPublicNameId(STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLinkedStrategiesByPublicNameIdRequest request) {
            return base.Channel.GetLinkedStrategiesByPublicNameId(request);
        }
        
        public string GetLinkedStrategiesByPublicNameId(STPC.DynamicForms.DecisionEngine.ScortoProxy.Ticket Ticket, int publicNameId) {
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLinkedStrategiesByPublicNameIdRequest inValue = new STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLinkedStrategiesByPublicNameIdRequest();
            inValue.Ticket = Ticket;
            inValue.publicNameId = publicNameId;
            STPC.DynamicForms.DecisionEngine.ScortoProxy.GetLinkedStrategiesByPublicNameIdResponse retVal = ((STPC.DynamicForms.DecisionEngine.ScortoProxy.ScoringServiceSoap)(this)).GetLinkedStrategiesByPublicNameId(inValue);
            return retVal.GetLinkedStrategiesByPublicNameIdResult;
        }
    }
}
