//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPC.DynamicForms.Web.Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STPC.DynamicForms.Web.Common.Messages.CustomMessages", typeof(CustomMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        public static string E0000 {
            get {
                return ResourceManager.GetString("E0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error procesando su solicitud. Por favor comunicarse con el administrador. 
        ///Id Soporte: {0}.
        /// </summary>
        public static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error, el o los objetos {0} no existen o no han sido creados en la base de datos. Por favor comunicarse con el administrador. 
        ///El origen de este comportamiento corresponde al controlador {1} en la ejecución de la acción {2}. 
        ///Id Soporte: {3}
        ///Detalle del error: {4}..
        /// </summary>
        public static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error intentando almacenar su archivo en el servidor, por favor comunicarse con el Administrador..
        /// </summary>
        public static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error intentando almacenar su archivo, el tamaño del archivo supera el máximo permitido..
        /// </summary>
        public static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error intentando almacenar su archivo, el formato o extension del archivo no es permitido..
        /// </summary>
        public static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error intentando almacenar su archivo, {0}.
        /// </summary>
        public static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error procesando su solicitud. 
        ///El origen de este comportamiento corresponde al controlador {0} en la ejecución de la acción {1}. 
        ///Id Soporte: {2}
        ///Detalle del error: {3}
        ///.
        /// </summary>
        public static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error llamando la estrategia: {0}.
        /// </summary>
        public static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find stored procedure.
        /// </summary>
        public static string EX0001 {
            get {
                return ResourceManager.GetString("EX0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object name.
        /// </summary>
        public static string EX0002 {
            get {
                return ResourceManager.GetString("EX0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store procedure de la tabla request.
        /// </summary>
        public static string EX0003 {
            get {
                return ResourceManager.GetString("EX0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña no válido.
        /// </summary>
        public static string EX0004 {
            get {
                return ResourceManager.GetString("EX0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los cambios se efectuaron satisfactoriamente.
        /// </summary>
        public static string G0001 {
            get {
                return ResourceManager.GetString("G0001", resourceCulture);
            }
        }
    }
}
