//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPC.DynamicForms.Web.Models.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-DG040MBBGBS\\SQLEXPRESS;Initial Catalog=STPC.DynamicForms.DB;Integ" +
            "rated Security=True")]
        public string STPC_DynamicForms_DBConnectionString {
            get {
                return ((string)(this["STPC_DynamicForms_DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE PROCEDURE [dbo].[spGetAvailableInterviewsUser]\r\n@userid nvarchar(20)\r\n\r\nAS" +
            "\r\nBEGIN\r\n\r\nDECLARE @FiltrosWhere nvarchar(1000)\r\nSELECT \r\n  @FiltrosWhere=\r\n  (C" +
            "ASE \r\n     WHEN ur.Role_Rolename IN (\'Administrador\',\'Gerente General\',\'Gerente " +
            "de negocio\') THEN  \'\'\r\n\t WHEN ur.Role_Rolename IN (\'Auxiliar\',\'Analista\') THEN \'" +
            "AND (t.UpdatedBy = \'\'\'+@userid+\'\'\' or t.AssignedTo = \'\'\'+@userid+\'\'\' OR t.Create" +
            "dBy=\'\'\'+@userid+\'\'\') AND WorkFlowState NOT IN (\'\'8DD826CA-1E70-4B3A-8566-09BEBB4" +
            "20312\'\')\'\r\n\t ELSE \'AND (t.UpdatedBy = \'\'\'+@userid+\'\'\' or t.AssignedTo = \'\'\'+@use" +
            "rid+\'\'\' OR t.CreatedBy=\'\'\'+@userid+\'\'\')\'\t \r\n\t END)  \r\n FROM  [user] u \r\nINNER JO" +
            "IN  [UserRole] ur ON ur.[User_Id]=u.Id\r\nWHERE u.Username=@userid\r\n\r\nDECLARE @SQL" +
            "String nvarchar (MAX)\r\n\t\r\nSET @SQLString=REPLACE(\'SELECT DISTINCT t.requestid as" +
            " [Solicitud],t.FormId,\r\n(CASE  WHEN m.f_requestid IS NULL AND s.Estado LIKE \'\'%A" +
            "nálisis%\'\' AND s.Estado NOT LIKE \'\'%EN ESTUDIO - Análisis financiero%\'\' THEN \'\'1" +
            "4A2D529-1A78-4C85-89C8-AE745F8DB31F\'\'\r\nWHEN WorkFlowState = \'\'280E83F0-BE5A-46AC" +
            "-8879-BECBF141643C\'\' THEN \'\'C266079C-DEF0-4131-801F-7975D3B1D318\'\'\r\nWHEN WorkFlo" +
            "wState = \'\'272FB96B-EDF5-422E-8692-FB4DDDE2DC93\'\' THEN \'\'70A84D8F-2586-41EC-836C" +
            "-456D7ADF752B\'\'\r\nWHEN WorkFlowState = \'\'DBF7ECC8-AF7E-4F55-B2C3-B654690D6D70\'\' T" +
            "HEN \'\'6D354B29-99E3-4398-A56E-BC906AF96DFF\'\'\r\nWHEN WorkFlowState = \'\'74616C36-13" +
            "F0-4F5B-A558-CAD07B082157\'\' THEN \'\'375B93A4-3F9F-459D-8570-2A557E4A8502\'\'\r\nWHEN " +
            "WorkFlowState = \'\'22939DC3-373C-4067-930C-0EF940AAFF35\'\' THEN \'\'1E2A11B5-EAC4-4C" +
            "B3-8C33-B5187F525264\'\'\r\nWHEN WorkFlowState = \'\'C7E18914-7B4F-415D-9CA4-9904B5526" +
            "73A\'\' THEN \'\'5D450DCD-DAC3-49F1-96A3-6BB2D1D23F1A\'\'\r\nWHEN WorkFlowState = \'\'ECF3" +
            "C63F-8E21-422C-A4D8-14C6298A9220\'\' THEN \'\'375B93A4-3F9F-459D-8570-2A557E4A8502\'\'" +
            "\r\nWHEN WorkFlowState in (\'\'5D40A1DC-9FF0-4678-AB0F-BEE34E9C6188\'\',\'\'9DD3F7BA-C00" +
            "4-4A54-A353-81678DC338A9\'\') THEN \'\'C266079C-DEF0-4131-801F-7975D3B1D318\'\'\r\nWHEN " +
            "WorkFlowState = \'\'5A8A48F5-A669-4676-8A6B-2BD32102420F\'\' THEN \'\'6491083C-7101-46" +
            "04-AD77-EAE81CF224DB\'\' \r\nWHEN WorkFlowState = \'\'CB4BEB62-564C-4CB5-AFBD-A79A33C6" +
            "4CA3\'\' THEN  \'\'1E2A11B5-EAC4-4CB3-8C33-B5187F525264\'\'\r\nWHEN WorkFlowState = \'\'85" +
            "5C7AB6-2586-464B-8F13-425592008EDA\'\' THEN  \'\'1E2A11B5-EAC4-4CB3-8C33-B5187F52526" +
            "4\'\'\r\nWHEN WorkFlowState = \'\'9601CF6E-5DA4-4D57-80B0-04EC2D7CA566\'\' THEN  \'\'3CE78" +
            "644-BA1E-4DFF-9860-499B025B5061\'\'\r\nWHEN WorkFlowState = \'\'7A54C168-5473-442A-8B1" +
            "1-3867F98B58B1\'\' THEN  \'\'375B93A4-3F9F-459D-8570-2A557E4A8502\'\'\r\nELSE T.PageFlow" +
            "Id END) AS [PageFlowId], t.requestid as [N Solicitud], \'\'Aliados\'\' AS [Tipo Nego" +
            "cio], \'\'Natural\'\' AS [Tipo Persona],\r\ns.Identificación, ltrim(s.[Nombre completo" +
            "]) as Nombre, s.Estado, s.[Tiempo (Min)]\r\nFROM vw_ListaTrabajoAliadosNatural s I" +
            "NNER JOIN request t ON t.requestid = s.Solicitud \r\nLEFT JOIN VW_UltimoEstablecim" +
            "iento_Aliados m ON t.requestid = m.f_requestid\r\nINNER JOIN  [user] u ON u.Userna" +
            "me=\'\'\'+@userid+\'\'\' INNER JOIN  [UserRole] ur ON ur.[User_Id]=u.Id WHERE 1=1  \'+@" +
            "FiltrosWhere+\'\r\nUNION ALL\',char(13),\' \')\r\n\r\nDECLARE @SQLString2 nvarchar (MAX)\r\n" +
            "\r\nSET @SQLString2=\r\nREPLACE(\'\r\nSELECT t.requestid as [Solicitud],t.FormId,\r\n(CAS" +
            "E  WHEN m.f_requestid IS NULL AND s.Estado LIKE \'\'%Análisis%\'\' AND s.Estado NOT " +
            "LIKE \'\'%EN ESTUDIO - Análisis financiero%\'\' THEN \'\'14A2D529-1A78-4C85-89C8-AE745" +
            "F8DB31F\'\'\r\nWHEN WorkFlowState = \'\'280E83F0-BE5A-46AC-8879-BECBF141643C\'\' THEN \'\'" +
            "C266079C-DEF0-4131-801F-7975D3B1D318\'\'\r\nWHEN WorkFlowState = \'\'272FB96B-EDF5-422" +
            "E-8692-FB4DDDE2DC93\'\' THEN \'\'70A84D8F-2586-41EC-836C-456D7ADF752B\'\'\r\nWHEN WorkFl" +
            "owState = \'\'DBF7ECC8-AF7E-4F55-B2C3-B654690D6D70\'\' THEN \'\'6D354B29-99E3-4398-A56" +
            "E-BC906AF96DFF\'\'\r\nWHEN WorkFlowState = \'\'74616C36-13F0-4F5B-A558-CAD07B082157\'\' " +
            "THEN \'\'375B93A4-3F9F-459D-8570-2A557E4A8502\'\'\r\nWHEN WorkFlowState = \'\'22939DC3-3" +
            "73C-4067-930C-0EF940AAFF35\'\' THEN \'\'1E2A11B5-EAC4-4CB3-8C33-B5187F525264\'\'\r\nWHEN" +
            " WorkFlowState = \'\'C7E18914-7B4F-415D-9CA4-9904B552673A\'\' THEN \'\'5D450DCD-DAC3-4" +
            "9F1-96A3-6BB2D1D23F1A\'\'\r\nWHEN WorkFlowState = \'\'ECF3C63F-8E21-422C-A4D8-14C6298A" +
            "9220\'\' THEN \'\'375B93A4-3F9F-459D-8570-2A557E4A8502\'\'\r\nWHEN WorkFlowState in (\'\'5" +
            "D40A1DC-9FF0-4678-AB0F-BEE34E9C6188\'\',\'\'9DD3F7BA-C004-4A54-A353-81678DC338A9\'\') " +
            "THEN \'\'C266079C-DEF0-4131-801F-7975D3B1D318\'\'\r\nWHEN WorkFlowState = \'\'5A8A48F5-A" +
            "669-4676-8A6B-2BD32102420F\'\' THEN \'\'6491083C-7101-4604-AD77-EAE81CF224DB\'\' \r\nWHE" +
            "N WorkFlowState = \'\'CB4BEB62-564C-4CB5-AFBD-A79A33C64CA3\'\' THEN  \'\'1E2A11B5-EAC4" +
            "-4CB3-8C33-B5187F525264\'\'\r\nWHEN WorkFlowState = \'\'855C7AB6-2586-464B-8F13-425592" +
            "008EDA\'\' THEN  \'\'1E2A11B5-EAC4-4CB3-8C33-B5187F525264\'\'\r\nWHEN WorkFlowState = \'\'" +
            "9601CF6E-5DA4-4D57-80B0-04EC2D7CA566\'\' THEN  \'\'F08045D8-7455-464F-B2E7-2D62999F4" +
            "333\'\'\r\nELSE T.PageFlowId END) AS [PageFlowId], t.requestid as [N Solicitud], \'\'A" +
            "liados\'\' AS [Tipo Negocio], \'\'Jurídica\'\' AS [Tipo Persona],\r\ns.Identificación, l" +
            "trim(s.[Nombre completo]) as Nombre, s.Estado,  s.[Tiempo (Min)] \r\nFROM [dbo].[R" +
            "equest] t with (nolock) inner join vw_ListaTrabajoAliadosJuridico s on s.Solicit" +
            "ud = t.RequestId LEFT JOIN VW_UltimoEstablecimiento_Aliados m ON t.requestid = m" +
            ".f_requestid\r\nINNER JOIN  [user] u ON u.Username=\'\'\'+@userid+\'\'\' INNER JOIN  [Us" +
            "erRole] ur ON ur.[User_Id]=u.Id WHERE 1=1  \'+@FiltrosWhere+\'\r\n UNION ALL\',char(1" +
            "3),\' \')\r\n\r\n\r\nDECLARE @SQLString3 nvarchar (MAX)\r\n\r\nSET @SQLString3=\r\nREPLACE(\'\r\n" +
            "SELECT t.requestid as [Solicitud]\r\n,t.FormId\r\n,CASE WHEN t.WorkFlowState = \'\'505" +
            "6C771-7766-4E4E-9CA2-967C3CA5EEED\'\' THEN \'\'53EB2B01-7F1C-4DAC-919F-8A5549319B32\'" +
            "\'\r\n      WHEN t.WorkFlowState = \'\'74616C36-13F0-4F5B-A558-CAD07B082157\'\' THEN \'\'" +
            "52DF2C70-157B-4B43-A2FD-D303A2560A4D\'\'\r\n\t  WHEN t.WorkFlowState = \'\'280E83F0-BE5" +
            "A-46AC-8879-BECBF141643C\'\' THEN \'\'8695FDF4-BE08-4271-AE7D-1EA487A1BFD9\'\'\r\n ELSE " +
            "t.PageFlowId END AS [PageFlowId]\r\n,t.requestid as [N Solicitud]\r\n,\'\'Venta Empres" +
            "arial\'\' AS [Tipo Negocio]\r\n, s.[Tipo Persona],\r\ns.Identificación\r\n,ltrim(s.[Nomb" +
            "re completo]) as Nombre\r\n,s.Estado,  s.[Tiempo (Min)] \r\nFROM [dbo].[Request] t W" +
            "ITH (NOLOCK)\r\nINNER JOIN VW_ListaTrabajoVentaEmpresarial s on s.Solicitud = t.Re" +
            "questId \r\nWHERE 1=1  \'+@FiltrosWhere+\' UNION ALL\',char(13),\' \')\r\n\r\nDECLARE @SQLS" +
            "tring4 nvarchar (MAX)\r\n\r\n\r\nSET @SQLString4=\r\nREPLACE(\'\r\nSELECT t.requestid as [S" +
            "olicitud],t.FormId,\r\nt.PageFlowId, t.requestid as [N Solicitud], \'\'Otros Medios " +
            "de Pago\'\' AS [Tipo Negocio], s.[Tipo Persona],\r\ns.Identificación, ltrim(s.[Nombr" +
            "e completo]) as Nombre, s.Estado,  s.[Tiempo (Min)] \r\nFROM [dbo].[Request] t wit" +
            "h (nolock) inner join VW_ListaTrabajoOtrosMediospago s on s.Solicitud = t.Reques" +
            "tId WHERE 1=1  \'+@FiltrosWhere+\' UNION ALL\',char(13),\' \')\r\n\r\nDECLARE @SQLString5" +
            " nvarchar (MAX)\r\n\r\nSET @SQLString5=\r\nREPLACE(\'\r\nSELECT t.requestid as [Solicitud" +
            "],t.FormId,\r\nt.PageFlowId, t.requestid as [N Solicitud], \'\'Inmobiliaria\'\' AS [Ti" +
            "po Negocio], s.[Tipo Persona],\r\ns.Identificación, ltrim(s.[Nombre completo]) as " +
            "Nombre, s.Estado,  s.[Tiempo (Min)] \r\nFROM [dbo].[Request] t with (nolock) inner" +
            " join VW_ListaTrabajoInmobiliaria s on s.Solicitud = t.RequestId WHERE 1=1  \'+@F" +
            "iltrosWhere+\' UNION ALL\',char(13),\' \')\r\n\r\n\r\nDECLARE @SQLString6 nvarchar (MAX)\r\n" +
            "\r\nSET @SQLString6=\r\nREPLACE(\'\r\nSELECT t.requestid as [Solicitud],t.FormId,\r\nt.Pa" +
            "geFlowId, t.requestid as [N Solicitud], \'\'Venta Institucional\'\' AS [Tipo Negocio" +
            "], s.[Tipo Persona],\r\ns.Identificación, ltrim(s.[Nombre completo]) as Nombre, s." +
            "Estado,  s.[Tiempo (Min)] \r\nFROM [dbo].[Request] t with (nolock) inner join  VW_" +
            "ListaTrabajoVentaInstitucional s on s.Solicitud = t.RequestId WHERE 1=1  \'+@Filt" +
            "rosWhere+\' ORDER BY 1 DESC\',char(13),\' \')\r\n\r\n\r\n--SELECT @SQLString,@SQLString2,@" +
            "SQLString3\r\n EXECUTE  (@SQLString + @SQLString2 + @SQLString3 + @SQLString4 + @S" +
            "QLString5 + @SQLString6 )\r\n\r\n\r\n \r\nEND\r\n")]
        public string SPMisSolicitudes {
            get {
                return ((string)(this["SPMisSolicitudes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CREATE PROCEDURE [dbo].[Insert_Request]
@FormId uniqueidentifier,
@WorkFlowState nvarchar(255) = null,
@PageFlowState nvarchar (255) = null,
@PageFlowId uniqueidentifier = null,
@Created datetime,
@CreatedBy nvarchar(255),
@Updated datetime,
@UpdatedBy nvarchar(255)= null,
@AssignedTo nvarchar(255)= null,
@AplicationNameId int= null
AS
BEGIN
insert into [dbo].[Request](
Created,
Updated,
FormId,
WorkFlowState,
PageFlowState,
PageFlowId,
CreatedBy,
UpdatedBy,
AssignedTo,
AplicationNameId
)
values(
@Created,
@Updated,
@FormId,
@WorkFlowState,
@PageFlowState,
@PageFlowId,
@CreatedBy,
@UpdatedBy,
@AssignedTo,
@AplicationNameId
)
SELECT SCOPE_IDENTITY() as RequestId
END
")]
        public string SPInsertRequest {
            get {
                return ((string)(this["SPInsertRequest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE PROCEDURE [dbo].[SearchRequests]\r\n@Created\tDateTime,\r\n@Updated\tDateTime,\r\n" +
            "@Created_End\tDateTime,\r\n@Updated_End\tDateTime,\t\r\n@RequestId\tint,\t\r\n@CreatedBy\tnv" +
            "archar(255),\t\r\n@UpdatedBy\tnvarchar(255),\t\r\n@WorkFlowState\tvarchar(255),\t\r\n@Hiera" +
            "rchies\tnvarchar(255), \t\r\n@UserName\tnvarchar(255),\t\r\n@DynamicWhere\tnvarchar(max)," +
            "\r\n@DynamicJoin\tnvarchar(max),\r\n@DynamicSelect\tnvarchar(max),\r\n@FormId\tuniqueiden" +
            "tifier,\r\n@SqlStringOutPut varchar(max) output\r\nAS\r\nBEGIN\r\n\r\nSET NOCOUNT ON\r\n\r\nDE" +
            "CLARE @FiltroPerfil nvarchar(1000)\r\nSELECT \r\n  @FiltroPerfil=\'\'\r\n  \r\n\r\n\r\nSET @Sq" +
            "lStringOutPut = \r\n\'SELECT request.[RequestId] as Solicitud,\r\n\t  request.[FormId]" +
            ",\r\n\t  request.[PageFlowId], \r\n\t  request.[RequestId] as [Num. Solicitud], \r\n\t \'\'" +
            "Natural\'\' [Tipo persona],\r\n      s.F_intNumeroIdentificacionPn as Identificación" +
            ",\r\n\t ltrim(rtrim(F_varPrimerApellidoPn))+\'\' \'\'+ltrim(rtrim(F_varPrimerNombrePn))" +
            "+\'\' \'\'+ltrim(rtrim(F_varSegundoApellidoPn))+\'\' \'\'+ltrim(rtrim(F_varSegundoNombre" +
            "Pn)) as [Nombre completo],\r\n\t e.StateName  as Estado\t \r\n  FROM [dbo].[Request] w" +
            "ith (nolock) inner join VW_InformacionBasica_Aliados s with (nolock)\r\n  on s.f_r" +
            "equestId = request.RequestId\r\n  inner join FormStates e with (nolock)\r\n  on requ" +
            "est.WorkFlowState = e.UId\r\n  INNER JOIN  [user] u ON u.Username=\'\'\'+@UserName+\'\'" +
            "\'\r\n  INNER JOIN  [UserRole] ur ON ur.[User_Id]=u.Id \'+@DynamicJoin\r\n  +\' WHERE 1" +
            "=1 \'+ @DynamicWhere\r\n  + CASE WHEN YEAR(@Created)>1900 THEN \' AND CONVERT(DATE,R" +
            "equest.Created) between \'\'\'+CONVERT(nvarchar,@Created,112)+\'\'\' AND \'\'\'+CONVERT(n" +
            "varchar,@Created_End,112)+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN YEAR(@Updated)>1900 TH" +
            "EN \' AND CONVERT(DATE,Request.Updated) between \'\'\'+CONVERT(nvarchar,@Updated,112" +
            ")+\'\'\' AND \'\'\'+CONVERT(nvarchar,@Updated_End,112)+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN" +
            " @RequestId>0 THEN \' AND Request.RequestId = \'+CONVERT(nvarchar,@RequestId) ELSE" +
            " \'\' END\r\n  + CASE WHEN @CreatedBy<>\'\' THEN \' AND Request.CreatedBy = \'\'\'+@Create" +
            "dBy+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN @UpdatedBy<>\'\' THEN \' AND Request.UpdatedBy " +
            "= \'\'\'+@UpdatedBy+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN @WorkFlowState<>\'\' THEN \' AND R" +
            "equest.WorkFlowState = \'\'\'+@WorkFlowState+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN @Hiera" +
            "rchies<>\'\' THEN \' AND o.[key]  IN (\'+@Hierarchies+\')\' ELSE \'\' END  \r\n  + @Filtro" +
            "Perfil\r\n  + \' UNION ALL\r\n  SELECT request.[RequestId] as Solicitud,\r\n\t  request." +
            "[FormId],\r\n\t  request.[PageFlowId], \r\n\t  request.[RequestId] as [Num. Solicitud]" +
            ",  \r\n\t  \'\'Juridico \'\'[Tipo persona],\r\n      s.F_intNitEmpresaPj as Identificació" +
            "n,\r\n\t ltrim(rtrim(F_varNombreEmpresaPj))  as [Nombre completo],\r\n\t e.StateName  " +
            "as Estado\t \r\n  FROM [dbo].[Request] with (nolock) inner join VW_InformacionBasic" +
            "aPJ_Aliados s with (nolock)\r\n  on s.f_requestId = request.RequestId\r\n  inner joi" +
            "n FormStates e with (nolock)\r\n  on request.WorkFlowState = e.UId\r\n   INNER JOIN " +
            " [user] u ON u.Username=\'\'\'+@UserName+\'\'\'\r\n  INNER JOIN  [UserRole] ur ON ur.[Us" +
            "er_Id]=u.Id \'+@DynamicJoin\r\n  +\' WHERE 1=1 \'+@DynamicWhere\r\n  + CASE WHEN YEAR(@" +
            "Created)>1900 THEN \' AND CONVERT(DATE,Request.Created) between \'\'\'+CONVERT(nvarc" +
            "har,@Created,112)+\'\'\' AND \'\'\'+CONVERT(nvarchar,@Created_End,112)+\'\'\'\' ELSE \'\' EN" +
            "D\r\n  + CASE WHEN YEAR(@Updated)>1900 THEN \' AND CONVERT(DATE,Request.Updated) be" +
            "tween \'\'\'+CONVERT(nvarchar,@Updated,112)+\'\'\' AND \'\'\'+CONVERT(nvarchar,@Updated_E" +
            "nd,112)+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN @RequestId>0 THEN \' AND Request.RequestI" +
            "d = \'+CONVERT(nvarchar,@RequestId) ELSE \'\' END\r\n  + CASE WHEN @CreatedBy<>\'\' THE" +
            "N \' AND Request.CreatedBy = \'\'\'+@CreatedBy+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN @Upda" +
            "tedBy<>\'\' THEN \' AND Request.UpdatedBy = \'\'\'+@UpdatedBy+\'\'\'\' ELSE \'\' END\r\n  + CA" +
            "SE WHEN @WorkFlowState<>\'\' THEN \' AND Request.WorkFlowState = \'\'\'+@WorkFlowState" +
            "+\'\'\'\' ELSE \'\' END\r\n  + CASE WHEN @Hierarchies<>\'\' THEN \' AND o.[key]  IN (\'+@Hie" +
            "rarchies+\')\' ELSE \'\' END  \r\n  + @FiltroPerfil\r\n  \r\n--  SELECT * FROM TempSearchR" +
            "equests order by 2\r\n  insert into TempSearchRequests\r\nselect newid(),GETDATE(),@" +
            "Updated,@Created_End,@Updated_End,@RequestId,@CreatedBy,@UpdatedBy,@WorkFlowStat" +
            "e,@Hierarchies,@UserName,@DynamicWhere,@DynamicJoin,@DynamicSelect,@FormId,@SqlS" +
            "tringOutPut\r\n\r\n--SELECT @SqlStringOutPut\r\n EXEC(@SqlStringOutPut)\r\n  --select * " +
            "from TempSearchRequests order by 2\r\n  --truncate table TempSearchRequests\r\n\r\n\r\n\r" +
            "\n\r\nEND\r\n")]
        public string SPSearchRequest {
            get {
                return ((string)(this["SPSearchRequest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE PROCEDURE [dbo].[Select_RequestById]\r\n@RequestId int\r\nAS\r\nBEGIN\r\nSELECT Re" +
            "questId,\r\nCreated,\r\nUpdated,\r\nFormId,\r\nWorkFlowState,\r\nPageFlowState,\r\nPageFlowI" +
            "d,\r\nCreatedBy,\r\nUpdatedBy\r\nfrom Request\r\nwhere RequestId = @RequestId\r\nEND\r\n")]
        public string SPSelect_RequestById {
            get {
                return ((string)(this["SPSelect_RequestById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CREATE PROCEDURE [dbo].[Update_Request]
@RequestId int,
@PageFlowState varchar(255),
@PageFlowId uniqueidentifier,
@Updated datetime,
@UpdatedBy varchar(255),
@WorkFlowState varchar(255)
AS
BEGIN
Update [dbo].[Request]	
set PageFlowState = @PageFlowState,
PageFlowId = @PageFlowId,
UpdatedBy = @UpdatedBy,
Updated = GETDATE(),
WorkFlowState=@WorkFlowState
where [RequestId] = @RequestId
END

")]
        public string SPUpdate_Request {
            get {
                return ((string)(this["SPUpdate_Request"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CREATE PROCEDURE [dbo].[GetUserFormPageActionsByState] (@formstateUID AS UNIQUEIDENTIFIER,@PageId AS UNIQUEIDENTIFIER,@username AS NVARCHAR(255))
AS
--Variables de prueba
--DECLARE @formstateUID AS UNIQUEIDENTIFIER
--DECLARE @PageId AS UNIQUEIDENTIFIER
--DECLARE @username AS NVARCHAR(255)
--SET @formstateUID='00000000-0000-0000-0000-000000000000' 
--SET @PageId='fb21dc1e-40e3-47e9-bcf5-3051f8e79f85'--
--SET @username='CC1'

/*
EXEC	 [dbo].[GetUserFormPageActionsByState] '00000000-0000-0000-0000-000000000000'
, 'fb21dc1e-40e3-47e9-bcf5-3051f8e79f85','CC1'
*/

SELECT DISTINCT FPA.Uid,fpa.Name,fpa.[Description] AS [description],fpa.Caption,fpa.IsAssociated,fpa.IsExecuteStrategy,fpa.PageId
	,fpa.DisplayOrder,fpa.[Save],fpa.GoToPageId,fpa.FormStatesUid,fpa.FormPage_Uid,fpa.ShowSuccessMessage
	,fpa.ShowFailureMessage,fpa.StrategyID
FROM dbo.FormPage FP
INNER JOIN dbo.FormPageActions FPA
ON FP.Uid=FPA.Pageid
INNER JOIN dbo.FormPageActionsByStates FPAS
ON FPA.Uid = FPAS.FormPageActionsUid
AND fpas.FormStatesUid=@formstateUID
INNER JOIN	dbo.FormPageActionsRoles fpar
ON fpa.Uid=fpar.FormPageActionsUid
INNER JOIN DBO.UserRole ur
ON ur.Role_Rolename=fpar.Rolename
INNER JOIN dbo.[User] 
ON [user].id=ur.[USER_ID]
WHERE  fp.Uid=@PageId
AND [user].Username=@username 
ORDER BY fpa.DisplayOrder")]
        public string SPGetUsersByStates {
            get {
                return ((string)(this["SPGetUsersByStates"]));
            }
        }
    }
}
